# -*- coding: utf-8 -*-
"""Sales Data Analysis & Business Insights Dashboard.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nDjZ_M0QdDc9TQEox4WRftWGJ13PxDVG

**Sales Data Analysis & Business Insights Dashboard**

1. problem statment :

   Businesses often lack clarity on sales performance across regions and time periods.

2. Objective :

   Analyze sales data to identify trends, seasonality, and performance gaps.

Step 1 : Dataset file uploading
"""

from google.colab import files

uploaded = files.upload()

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

plt.style.use('default')

import pandas as pd

df = pd.read_csv("sales_data_sample.csv", encoding='latin1')
df.head()

"""Step 2 : Data Cleaning"""

df.drop_duplicates(inplace=True)
df.isnull().sum()

df['ORDERDATE'] = pd.to_datetime(df['ORDERDATE'])

"""Step 3 : Feature Engineering"""

df['Year'] = df['ORDERDATE'].dt.year
df['Month'] = df['ORDERDATE'].dt.month
# df['Profit Margin'] = df['Profit'] / df['Sales'] # 'Profit' column not found in data

"""Step 4 : Exploratory Data Analysis (EDA)"""

df.groupby('TERRITORY')['SALES'].sum()
df.groupby('PRODUCTLINE')['SALES'].sum()

"""Step 5 : Sales Trend Analysis"""

monthly_sales = df.groupby(['Year','Month'])['SALES'].sum()
monthly_sales.plot()

"""Step 6 : Data Visualization"""

import seaborn as sns
sns.barplot(x='TERRITORY', y='SALES', data=df)

"""**Business Insights & Conclusion :**

 1. West region contributes highest sales.

 2. Technology category shows high sales but low profit margin.

 3. Sales peaks in November–December.



"""